config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('encore/', include('encore.urls')),
    path('', include('main.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name = 'index'),  # /페이지에 해당하는 urlpatterns
]

encore/urls.py
from django.urls import path
from . import views

app_name = 'encore'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:question_id>/', views.detail, name = 'detail'),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index)
]

encore/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    subject = models.CharField(max_length=200)  # 질문의 제목. 글자 수를 제한가고 싶을때는 CharField를 사용
    content = models.TextField()  # 질문의 내용
    create_date = models.DateTimeField()  # 질문 작성일

    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)  # 질문(어떤 질문의 답변인지를 표시). on_delete=models.CASCADE = 질문이 삭제되면 답변도 삭제
    content = models.TextField()  # 답변의 내용
    create_date = models.DateTimeField()  # 답변 작성일

encore/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from .models import Question

# Create your views here.
def index(request):
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list' : question_list}
    return render(request, 'encore/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'encore/question_detail.html', context)

templates/encore/question_detail.html
<h1>{{question.subject}}</h1>

<div>
    {{question.content}}
</div>

templates/encore/question_list.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

<!--{% if question_list %} &lt;!&ndash; template tag &ndash;&gt;-->
<!--    <ul>-->
<!--    {% for question in question_list %}-->
<!--        <li><a href="{% url 'encore:detail' question.id%}">{{ question.subject }}</a></li>-->
<!--        &lt;!&ndash;pybo:detail, pybo(namespace)의 detail(별칭)&ndash;&gt;-->
<!--    {% endfor %}-->
<!--    </ul>-->
<!--{% else %}-->
<!--    <p>질문이 없습니다.</p>-->
<!--{% endif %}-->

<div class = "container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'pybo:detail' question.id %}">
                    {{ question.subject }}
                </a>
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {%endfor%}
        {%else%}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {%endif%}
        </tbody>
    </table>
</div>