config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('encore/', include('encore.urls')),
    path('', include('main.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name = 'index'),  # /페이지에 해당하는 urlpatterns
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index)
]

pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'  # 서로 다른 앱이 같은 url매핑 별칭을 쓸 때 중복문제 발생. namespace 도입

urlpatterns = [
    path('', views.index, name = 'index'),  # name 속성으로 url 매핑에 별칭만들기
    path('<int:question_id>/', views.detail, name = 'detail'),  # /pybo/2/ 요청시, question_id에 2가 저장 --> views.detail함수 실행
    path('answer/create/<int:question_id>', views.answer_create, name = 'answer_create'),
    path('question/create/', views.question_create, name = 'question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name = 'question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name = 'question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name = 'answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name = 'answer_delete'),
]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)  # 질문의 제목. 글자 수를 제한가고 싶을때는 CharField를 사용
    content = models.TextField()  # 질문의 내용
    create_date = models.DateTimeField()  # 질문 작성일
    modify_date = models.DateTimeField(null=True, blank=True)  # 수정일

    def __str__(self):
        return self.subject
class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)  # 질문(어떤 질문의 답변인지를 표시). on_delete=models.CASCADE = 질문이 삭제되면 답변도 삭제
    content = models.TextField()  # 답변의 내용
    create_date = models.DateTimeField()  # 답변 작성일
    modify_date = models.DateTimeField(null=True, blank=True)  # 수정일

pybo/forms.py
from django import forms
from pybo.models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        # widgets = {
        #     'subject' : forms.TextInput(attrs={'class' : 'form-control'}),
        #     'content' : forms.Textarea(attrs={'class' : 'form-control', 'rows' : 10})
        # }
        labels = {
            'subject' : '제목',
            'content' : '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content' : '답변내용',
        }

pybo/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Question, Answer
from .forms import QuestionForm, AnswerForm

# Create your views here.
def index(request):
    """
    pybo 목록 출력
    render 함수는 context에 있는 모델 데이터를 pybo/quesion_list.html(템플렛이라고 부른다)파일에 적용하여 HTML코드로 변환
    """
    # 입력 인자
    page = request.GET.get('page', '1')  # 페이지

    # 조회
    question_list = Question.objects.order_by('-create_date')  # 작성일시 역순으로

    # 페이징 처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개 보여주기
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj}
    return render(request, 'pybo/question_list.html', context)
    # return HttpResponse("안녕하세요! pybo에 오신것을 환영합니다.")

def detail(request, question_id):
    question = get_object_or_404(Question, pk = question_id)  # Question.objects.get(id=question_id)
    context = {'question' : question}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id = question_id)
    else:
        form = AnswerForm()
    context = {'question' : question, 'form' : form}
    return render(request ,'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm() # request.method가 'GET'인 경우 호출
    context = {'form' : form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    """pybo 질문 수정"""
    question = get_object_or_404(Question, pk = question_id)
    if request.user != question.author:
        messages.error(reqeust, '수정 권한이 없습니다.')
        return redirect('pybo:detail', question_id=question_id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)  # instance를 이용하여 기존 값을 폼에 채워넣는다.
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now()  #수정일 저장
            question.save()
            return redirect('pybo:detail', question_id=question_id)
    else:
        form = QuestionForm(instance=question)
    context = {'form':form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    """질문 삭제"""
    question = get_object_or_404(Question, pk = question_id)
    if request.user != question.author:
        messages.error(request, "삭제권한이 없습니다.")
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """pybo 답변 수정"""
    answer = get_object_or_404(Answer, pk = answer_id)
    if request.user != answer.author:
        messages.error(reqeust, '수정 권한이 없습니다.')
        return redirect('pybo:detail', question_id=answer.question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)  # instance를 이용하여 기존 값을 폼에 채워넣는다.
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()  #수정일 저장
            answer.save()
            return redirect('pybo:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer':answer, 'form':form}
    return render(request, 'pybo/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    """답변 삭제"""
    answer = get_object_or_404(Answer, pk = answer_id)
    if request.user != answer.author:
        messages.error(request, "삭제권한이 없습니다.")
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

templates/pybo/answer_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        <!-- 오류 표시 -->
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}
<!--
{%load static%}

<link rel="stylesheet" type="text/css" href="{%static 'style.css'%}">
<h1>{{question.subject}}</h1>
<div>
    {{question.content}}
</div>
<h5>{{question.answer_set.count}}개의 답변이 있습니다.</h5>
<div>
    <ul>
        {% for answer in question.answer_set.all %}
        <li>{{answer.content}}</li>
        {%endfor%}
    </ul>
</div>
<form action = "{% url 'pybo:answer_create' question.id %}" method = "post">
    {%csrf_token%} &lt;!&ndash;form 밑에 필수!, 보안 관련 : form 엘리먼트로 전송된 데이터(답변)가 실제로 웹브라우저에서 작성된 데이터인지 판단 검사&ndash;&gt;
    <textarea name = "content" id = "content" rows = "15"></textarea>
    <input type = "submit" value = "답변 등록">
</form>-->

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container my-3">
    <!-- 질문 제목 -->
    <h2 class="border-bottom py-2">{{question.subject}}</h2>
    <div class="card my-3">
        <div class="card-body">
            <!-- 질문 내용 -->
            <div class="card-text" style="white-space: pre-line;">
                {{question.content}}
            </div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                <div class="badge badge-light p-2 text-left mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{question.modify_date}}</div>  <!-- 질문 수정일 -->
                </div>
                {% endif %}
                <div class="badge badge-light p-2 text-left">
                    <!-- 질문 작성자 -->
                    <div class="mb-2">{{ question.author.username }}</div>
                    <!-- 질문 생성일 -->
                    <div>{{question.create_date}}</div>
                </div>
            </div>
            <!-- 질문 수정 버튼 -->
            {% if request.user == question.author %}
            <div class="my-3">
                <a href="{% url 'pybo:question_modify' question.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'pybo:question_delete' question.id %}">삭제</a>
            </div>
            {% endif %}
        </div>
    </div>
    <!-- 답변 파트 -->
    <h5 class="border-bottom my-3 py-2">
        {{ question.answer_set.count}}개의 답변이 있습니다.
    </h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <!-- 답변 내용 -->
            <div class="card-text" style="white-space: pre-line;">
                {{answer.content}}
            </div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge badge-light p-2 text-left mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{answer.modify_date}}</div>  <!-- 질문 수정일 -->
                </div>
                {% endif %}
                <div class="badge badge-light p-2 text-left">
                    <!-- 답변 작성자 -->
                    <div class="mb-2">{{ answer.author.username}}</div>
                    <!-- 답변 작성일 -->
                    <div>{{answer.create_date}}</div>
                </div>
            </div>
            <!-- 답변 수정 -->
            {% if request.user == answer.author %}
            <div class="my-3">
                <a href="{% url 'pybo:answer_modify' answer.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'pybo:answer_delete' answer.id %}">삭제</a>
            </div>
            {% endif %}
        </div>
    </div>
    {%endfor%}
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 답변 입력란 -->
        <div class="form-group">
            <textarea name="content" id="content" {% if not user.is_authenticated %}disabled{% endif %} class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문 등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <!-- 오류 표시 -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong> {{ field.label }}</strong>
                {{ field.errors  }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 end -->
        <!--{{ form.as_p }}-->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}"
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<!--{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">-->

<!--{% if question_list %} &lt;!&ndash; template tag &ndash;&gt;-->
<!--    <ul>-->
<!--    {% for question in question_list %}-->
<!--        <li><a href="{% url 'pybo:detail' question.id%}">{{ question.subject }}</a></li>-->
<!--        &lt;!&ndash;pybo:detail, pybo(namespace)의 detail(별칭)&ndash;&gt;-->
<!--    {% endfor %}-->
<!--    </ul>-->
<!--{% else %}-->
<!--    <p>질문이 없습니다.</p>-->
<!--{% endif %}-->

<div class = "container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</td>
            <!-- ...paginator.count : 전체 게시물 개수, ...start_index : 시작 인덱스, ...forloop... : 루프내 현재 인덱스 0부터 시작-->
            <td class="text-left">
                <a href="{% url 'pybo:detail' question.id %}">
                    {{ question.subject }}
                </a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger" small ml-2>
                    {{ question.answer_set.count }}
                </span>
                {% endif %}
            </td>
            <td>{{ question.author.username }}</td>
            <td>{{ question.create_date }}</td>
        </tr>
        {%endfor%}
        {%else%}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {%endif%}
        </tbody>
    </table>

    <!-- 페이징 처리 -->
    <ul class="pagination justify-content-center">
        <!-- 이전 페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.previous_page_number }}">
                이전
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지 리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        <!-- 현재 페이지 기준 좌우로 5개 -->
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page{{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}"> {{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음 페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_page_number }}">
                다음
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>

    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">
        질문 등록하기
    </a>
</div>
{% endblock %}