common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = 'common/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name = 'logout'),
    path('signup/', views.signup, name = 'signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('encore/', include('encore.urls')),
    path('', include('main.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name = 'index'),  # /페이지에 해당하는 urlpatterns
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index)
]

pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'  # 서로 다른 앱이 같은 url매핑 별칭을 쓸 때 중복문제 발생. namespace 도입

urlpatterns = [
    path('', views.index, name = 'index'),  # name 속성으로 url 매핑에 별칭만들기
    path('<int:question_id>/', views.detail, name = 'detail'),  # /pybo/2/ 요청시, question_id에 2가 저장 --> views.detail함수 실행
    path('answer/create/<int:question_id>', views.answer_create, name = 'answer_create'),
    path('question/create/', views.question_create, name = 'question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name = 'question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name = 'question_delete'),
    path('answer/modify/<int:answer_id>/', views.answer_modify, name = 'answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name = 'answer_delete'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <!-- required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, intial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, Pybo!</title>
</head>
<body>
<!-- 내비게이션 바 -->
{% include "navbar.html" %} <!--특정영역 분리에 이용. 중복 사용되는 영역일때 유용하다-->
<!-- 기본 템플렛 안에 삽입될 내용 start -->
{% block content %}
{% endblock %}
<!-- 기본 템플렛에 들어갈 내용 end-->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바 스크립트 start-->
{% block script %}
{% endblock %}
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류(입력값 누락/오류)를 출력 -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}  <!-- 넌필드 오류(입력값에 관계없이 오류)를 출력 -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!--내비게이션 바-->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}" >Pybo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃) </a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>